services:
  app:
    build: .
    container_name: meu-sistema-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  db:
    image: postgres:16
    container_name: meu-sistema-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: meu_sistema
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
