"use client"
import { useEffect, useMemo, useRef, useState } from "react"
import { useSearchParams } from "next/navigation"
import { Check, Loader2, PackageSearch, Plus, ReceiptText, Search, ShoppingCart, Trash2, UserRound, X } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"
import type { RegisteredProduct } from "@/src/domain/catalog/registered-product"
import type { RegisteredClient } from "@/src/domain/partners/registered-client"
import type { SalesOrder } from "@/src/domain/sales/sales-document"
import type { CompletedSale, PaymentMethod } from "@/src/domain/sales/checkout"

type Mode = "products" | "orders"
type CartItem = { productId: string; code: string; name: string; unit: string; quantity: number; price: number; discount: number; available: number }
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" })
const canInvoice = (order: SalesOrder) => order.status === "OPEN" || order.status === "CONFIRMED"

export function WebCheckoutContent() {
  const params = useSearchParams(), searchRef = useRef<HTMLInputElement>(null)
  const [mode, setMode] = useState<Mode>("products"), [query, setQuery] = useState("")
  const [products, setProducts] = useState<RegisteredProduct[]>([]), [orders, setOrders] = useState<SalesOrder[]>([])
  const [clients, setClients] = useState<RegisteredClient[]>([]), [methods, setMethods] = useState<PaymentMethod[]>([])
  const [cart, setCart] = useState<CartItem[]>([]), [order, setOrder] = useState<SalesOrder | null>(null)
  const [clientId, setClientId] = useState("anonymous"), [generalDiscount, setGeneralDiscount] = useState(0)
  const [methodId, setMethodId] = useState(""), [received, setReceived] = useState(0)
  const [loading, setLoading] = useState(true), [submitting, setSubmitting] = useState(false), [message, setMessage] = useState("")
  useEffect(() => { Promise.all([
    fetch("/api/products", { cache: "no-store" }).then(check).then(r => r.json()), fetch("/api/sales/orders", { cache: "no-store" }).then(check).then(r => r.json()),
    fetch("/api/clients", { cache: "no-store" }).then(check).then(r => r.json()), fetch("/api/sales/checkout/payment-methods", { cache: "no-store" }).then(check).then(r => r.json()),
  ]).then(([p,o,c,m]) => { setProducts(p); setOrders(o); setClients(c); setMethods(m); setMethodId(m[0]?.id ?? "") }).catch(e => setMessage(e.message)).finally(() => setLoading(false)) }, [])
  useEffect(() => { const id=params.get("pedidoId"); if (!id || loading) return; fetch(`/api/sales/orders/${id}`, { cache:"no-store" }).then(check).then(r=>r.json()).then(loadOrder).catch(e=>setMessage(e.message)) }, [loading, params])
  const productResults = useMemo(() => { const term=query.trim().toLocaleLowerCase("pt-BR"); return !term ? [] : products.filter(p => `${p.name} ${p.internalCode} ${p.barcode ?? ""}`.toLocaleLowerCase("pt-BR").includes(term)).slice(0,30) }, [query, products])
  const orderResults = useMemo(() => { const term=query.trim().toLocaleLowerCase("pt-BR"); return !term ? [] : orders.filter(o => canInvoice(o) && `${o.number} ${o.id} ${o.clientName} ${o.clientDocument ?? ""}`.toLocaleLowerCase("pt-BR").includes(term)).slice(0,30) }, [query, orders])
  const subtotal=cart.reduce((sum,i)=>sum+i.quantity*i.price,0), itemDiscount=cart.reduce((sum,i)=>sum+i.discount,0), freight=order?.freight ?? 0
  const total=Math.max(0,subtotal-itemDiscount-generalDiscount+freight), selectedMethod=methods.find(m=>m.id===methodId), change=Math.max(0,received-total)
  function addProduct(product: RegisteredProduct) { if (order) return; setCart(current => { const found=current.find(i=>i.productId===product.id); return found ? current.map(i=>i.productId===product.id?{...i,quantity:i.quantity+1}:i) : [...current,{productId:product.id,code:product.internalCode,name:product.name,unit:product.unitOfMeasure,quantity:1,price:product.salePrice,discount:0,available:product.stockAvailable}] }); setQuery(""); requestAnimationFrame(()=>searchRef.current?.focus()) }
  function loadOrder(value: SalesOrder) { if (!canInvoice(value)) { setMessage("Este pedido nao esta disponivel para faturamento."); return } setOrder(value); setClientId(value.clientId); setGeneralDiscount(value.generalDiscount); setCart(value.items.map(i=>({productId:i.productId,code:i.productCode,name:i.productName,unit:i.unitOfMeasure,quantity:i.quantity,price:i.unitPrice,discount:i.discount,available:0}))); setMode("orders"); setQuery(""); setMessage("") }
  function clear() { setOrder(null); setCart([]); setClientId("anonymous"); setGeneralDiscount(0); setReceived(0); setMessage(""); setMode("products"); searchRef.current?.focus() }
  async function complete() { if (!cart.length || !methodId) return setMessage("Adicione itens e selecione a forma de pagamento."); setSubmitting(true); setMessage(""); try { const response=await fetch("/api/sales/checkout/complete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({salesOrderId:order?.id??null,clientId:clientId==="anonymous"?null:clientId,generalDiscount,notes:order?.notes??"",items:cart.map(i=>({productId:i.productId,quantity:i.quantity,discount:i.discount})),payments:[{paymentMethodId:methodId,amount:total,receivedAmount:selectedMethod?.allowsChange?Math.max(total,received):total,installments:1}]})}); const data=await response.json(); if(!response.ok) throw new Error(data?.message??"Nao foi possivel finalizar a venda."); const sale=data as CompletedSale; clear(); setMessage(`Venda #${sale.number} finalizada com sucesso.`) } catch(e){setMessage(e instanceof Error?e.message:"Erro ao finalizar.")} finally {setSubmitting(false)} }
  return <div className="flex min-h-[calc(100vh-3.5rem)] flex-col gap-4 bg-muted/30 p-4 lg:p-6">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm text-muted-foreground">Vendas &gt; Caixa Web</p><h1 className="text-2xl font-semibold">Caixa Web</h1><p className="text-sm text-muted-foreground">Operador: admin</p></div><Button variant="outline" onClick={clear} disabled={!cart.length}><X className="size-4" />Limpar venda</Button></div>
    {message && <div className="rounded-md border bg-card px-4 py-3 text-sm" role="status">{message}</div>}
    <div className="grid flex-1 gap-4 xl:grid-cols-[minmax(340px,0.9fr)_minmax(560px,1.35fr)]">
      <Card className="min-h-[420px]"><CardHeader className="space-y-3 pb-3"><div className="flex items-center justify-between"><CardTitle className="text-base">Pesquisa</CardTitle>{loading&&<Loader2 className="size-4 animate-spin" />}</div><Tabs value={mode} onValueChange={v=>{setMode(v as Mode);setQuery("")}}><TabsList className="grid w-full grid-cols-2"><TabsTrigger value="products"><PackageSearch className="size-4" />Produtos</TabsTrigger><TabsTrigger value="orders"><ReceiptText className="size-4" />Pedidos</TabsTrigger></TabsList></Tabs><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input ref={searchRef} autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder={mode==="products"?"Nome, codigo interno ou codigo de barras":"Numero, codigo ou cliente"} className="pl-9" disabled={!!order}/></div></CardHeader><CardContent className="space-y-2">
        {!query&&!loading&&<div className="flex min-h-48 flex-col items-center justify-center text-center text-muted-foreground"><Search className="mb-3 size-8"/><p className="font-medium text-foreground">Inicie uma pesquisa</p><p className="max-w-xs text-sm">{mode==="products"?"Localize produtos por nome, codigo ou codigo de barras.":"Localize pedidos em aberto por numero ou cliente."}</p></div>}
        {query&&(mode==="products"?productResults:orderResults).length===0&&!loading&&<div className="py-16 text-center text-sm text-muted-foreground">Nenhum resultado encontrado.</div>}
        {mode==="products"&&productResults.map(p=><button key={p.id} onClick={()=>addProduct(p)} className="flex w-full items-center justify-between gap-3 rounded-lg border bg-card p-3 text-left transition-colors hover:bg-accent"><div><div className="flex items-center gap-2"><span className="font-medium">{p.name}</span><Badge variant="outline">{p.internalCode}</Badge></div><p className="text-xs text-muted-foreground">{p.barcode||"Sem codigo de barras"} · {p.unitOfMeasure} · Estoque {p.stockAvailable}</p></div><div className="text-right"><p className="font-semibold">{money.format(p.salePrice)}</p><Plus className="ml-auto size-4 text-primary"/></div></button>)}
        {mode==="orders"&&orderResults.map(o=><button key={o.id} onClick={()=>loadOrder(o)} className="flex w-full items-center justify-between gap-3 rounded-lg border bg-card p-3 text-left hover:bg-accent"><div><p className="font-medium">Pedido #{o.number}</p><p className="text-xs text-muted-foreground">{o.clientName} · {new Date(`${o.issueDate}T00:00:00`).toLocaleDateString("pt-BR")}</p></div><div className="text-right"><Badge variant="outline">Disponivel</Badge><p className="mt-1 font-semibold">{money.format(o.total)}</p></div></button>)}
      </CardContent></Card>
      <div className="flex min-w-0 flex-col gap-4"><Card className="flex min-h-[380px] flex-1 flex-col"><CardHeader className="border-b pb-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="text-base">{order?`Faturando pedido nº ${order.number}`:"Venda direta"}</CardTitle><p className="mt-1 text-xs text-muted-foreground">{cart.length} {cart.length===1?"item":"itens"} no carrinho</p></div>{order&&<Button size="sm" variant="outline" onClick={clear}>Remover pedido</Button>}</div><div><Label className="mb-1.5 block text-xs">Cliente</Label><Select value={clientId} onValueChange={setClientId} disabled={!!order}><SelectTrigger><UserRound className="size-4"/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="anonymous">Consumidor nao identificado</SelectItem>{clients.map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></div></CardHeader><CardContent className="flex-1 p-0">
        {!cart.length?<div className="flex h-72 flex-col items-center justify-center text-muted-foreground"><ShoppingCart className="mb-3 size-9"/><p className="font-medium text-foreground">Carrinho vazio</p><p className="text-sm">Pesquise e adicione um produto.</p></div>:<div className="divide-y">{cart.map(item=><div key={item.productId} className="grid gap-3 p-4 sm:grid-cols-[1fr_100px_110px_110px_auto] sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><p className="font-medium">{item.name}</p><Badge variant="secondary">{item.code}</Badge></div><p className="text-xs text-muted-foreground">{item.unit} · {money.format(item.price)} por unidade</p></div><div><Label className="text-xs">Quantidade</Label><Input type="number" min="0.0001" step="0.0001" value={item.quantity} disabled={!!order} onChange={e=>setCart(c=>c.map(i=>i.productId===item.productId?{...i,quantity:Math.max(.0001,Number(e.target.value))}:i))}/></div><div><Label className="text-xs">Desconto</Label><Input type="number" min="0" max={item.quantity*item.price} step="0.01" value={item.discount} disabled={!!order} onChange={e=>setCart(c=>c.map(i=>i.productId===item.productId?{...i,discount:Math.min(i.quantity*i.price,Math.max(0,Number(e.target.value)))}:i))}/></div><div className="text-right"><p className="text-xs text-muted-foreground">Subtotal</p><p className="font-semibold">{money.format(item.quantity*item.price-item.discount)}</p>{item.discount>0&&<p className="text-xs text-muted-foreground">Desconto {money.format(item.discount)}</p>}</div><Button variant="ghost" size="icon" aria-label={`Remover ${item.name}`} disabled={!!order} onClick={()=>setCart(c=>c.filter(i=>i.productId!==item.productId))}><Trash2 className="size-4 text-destructive"/></Button></div>)}</div>}
      </CardContent></Card>
      <Card><CardContent className="grid gap-4 p-4 md:grid-cols-[1fr_1fr_auto] md:items-end"><div><Label>Forma de pagamento</Label><Select value={methodId} onValueChange={setMethodId}><SelectTrigger><SelectValue placeholder="Selecione"/></SelectTrigger><SelectContent>{methods.map(m=><SelectItem key={m.id} value={m.id}>{m.name}</SelectItem>)}</SelectContent></Select></div>{selectedMethod?.allowsChange?<div><Label>Valor recebido</Label><Input type="number" min={total} step="0.01" value={received||""} onChange={e=>setReceived(Number(e.target.value))}/><p className="mt-1 text-xs text-muted-foreground">Troco: {money.format(change)}</p></div>:<div className="grid grid-cols-2 gap-4 text-sm"><div><p className="text-muted-foreground">Subtotal</p><p>{money.format(subtotal)}</p></div><div><p className="text-muted-foreground">Descontos</p><p>{money.format(itemDiscount+generalDiscount)}</p></div></div>}<div className="min-w-52"><p className="text-sm text-muted-foreground">Total da venda</p><p className="mb-3 text-3xl font-bold text-primary">{money.format(total)}</p><Button size="lg" className="w-full" disabled={!cart.length||submitting||(!!selectedMethod?.allowsChange&&received<total)} onClick={complete}>{submitting?<Loader2 className="size-4 animate-spin"/>:<Check className="size-4"/>}Finalizar venda</Button></div></CardContent></Card></div>
    </div></div>
}
async function check(response: Response) { if(!response.ok){const data=await response.json().catch(()=>null);throw new Error(data?.message??"Nao foi possivel carregar os dados.")}return response }
